# Собираем в гошке
FROM golang:1.22 as build

ENV BIN_FILE /opt/calendar/test_container
ENV CODE_DIR /go/src/

WORKDIR ${CODE_DIR}

#Кэшируем слои с модулями
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . ${CODE_DIR}

# Собираем статический бинарник Go (без зависимостей на Си API),
# иначе он не будет работать в alpine образе.
ARG LDFLAGS
RUN CGO_ENABLED=0 go build \
        -ldflags "$LDFLAGS" \
        -o ${BIN_FILE} tests/main.go

# На выходе тонкий образ
FROM alpine:3.9

LABEL ORGANIZATION="OTUS Online Education"
LABEL SERVICE="test_container"
LABEL MAINTAINERS="student@otus.ru"

ENV BIN_FILE "/opt/calendar/test_container"
COPY --from=build ${BIN_FILE} ${BIN_FILE}

CMD ${BIN_FILE} -port 50051