[logger]
level = "info"

[server]
host = "localhost"
port = 8080
handlerTimeoutS = 1
writeTimeoutMS = 500
readTimeoutMS = 500

[grpc]
port = 50051

[db]
# for docker
host = "db"
name = "calendar"
user = "user1"
pass = "pass"
poolSize = 5
maxConnLifeTime = 100

[storage]
type = "mem"
# type = "sql"
