// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/eventService.proto

package eventpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId             string               `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	HoursBeforeToNotify  int32                `protobuf:"varint,7,opt,name=hours_before_to_notify,json=hoursBeforeToNotify,proto3" json:"hours_before_to_notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Event) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Event) GetHoursBeforeToNotify() int32 {
	if m != nil {
		return m.HoursBeforeToNotify
	}
	return 0
}

type AddRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type AddResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	EventID              string   `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *AddResponse) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

type UpdateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DeleteRequest struct {
	EventID              string   `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

type DeleteResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetAllResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6284ed46706044b7, []int{7}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*AddRequest)(nil), "event.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "event.AddResponse")
	proto.RegisterType((*UpdateRequest)(nil), "event.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "event.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "event.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "event.DeleteResponse")
	proto.RegisterType((*GetAllResponse)(nil), "event.GetAllResponse")
}

func init() {
	proto.RegisterFile("api/eventService.proto", fileDescriptor_6284ed46706044b7)
}

var fileDescriptor_6284ed46706044b7 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x13, 0xe2, 0x24, 0x93, 0x34, 0x12, 0x4b, 0x89, 0x2c, 0xf7, 0x80, 0x65, 0x71, 0x30,
	0x17, 0x07, 0x25, 0x02, 0x54, 0x71, 0x40, 0xa9, 0x12, 0xa1, 0x5e, 0x38, 0x98, 0x72, 0xe1, 0x62,
	0x39, 0xdd, 0x49, 0xbb, 0x92, 0xe3, 0x35, 0xde, 0x75, 0xa5, 0x3e, 0x07, 0x8f, 0xc9, 0x4b, 0xa0,
	0xcc, 0xda, 0xa9, 0xdd, 0x4a, 0x54, 0x1c, 0xe7, 0xfb, 0x99, 0x9f, 0x4f, 0xbb, 0x30, 0x4b, 0x72,
	0x31, 0xc7, 0x3b, 0xcc, 0xf4, 0x77, 0x2c, 0xee, 0xc4, 0x35, 0x86, 0x79, 0x21, 0xb5, 0x64, 0x7d,
	0xc2, 0xdc, 0x37, 0x37, 0x52, 0xde, 0xa4, 0x38, 0x27, 0x70, 0x5b, 0xee, 0xe6, 0x5a, 0xec, 0x51,
	0xe9, 0x64, 0x9f, 0x1b, 0x9d, 0x7b, 0xf6, 0x58, 0x80, 0xfb, 0x5c, 0xdf, 0x1b, 0xd2, 0xff, 0xdd,
	0x85, 0xfe, 0xe6, 0xd0, 0x87, 0x4d, 0xa1, 0x2b, 0xb8, 0x63, 0x79, 0x56, 0x30, 0x8a, 0xba, 0x82,
	0xb3, 0x53, 0xe8, 0x6b, 0xa1, 0x53, 0x74, 0xba, 0x04, 0x99, 0x82, 0x9d, 0x03, 0x28, 0x9d, 0x14,
	0x3a, 0xe6, 0x89, 0x46, 0xa7, 0xe7, 0x59, 0xc1, 0x78, 0xe1, 0x86, 0x66, 0x42, 0x58, 0x4f, 0x08,
	0xaf, 0xea, 0x15, 0xa2, 0x11, 0xa9, 0xd7, 0x89, 0x46, 0xf6, 0x01, 0x86, 0x98, 0x71, 0x63, 0x7c,
	0xf1, 0xac, 0x71, 0x80, 0x19, 0x27, 0x9b, 0x07, 0x63, 0x8e, 0xea, 0xba, 0x10, 0xb9, 0x16, 0x32,
	0x73, 0xfa, 0xb4, 0x4d, 0x13, 0x62, 0x67, 0x30, 0x4a, 0x4a, 0x7d, 0x2b, 0x8b, 0x58, 0x70, 0xc7,
	0x26, 0x7e, 0x68, 0x80, 0x4b, 0xce, 0x96, 0x30, 0xbb, 0x95, 0x65, 0xa1, 0xe2, 0x2d, 0xee, 0x64,
	0x81, 0xb1, 0x96, 0x71, 0x26, 0xb5, 0xd8, 0xdd, 0x3b, 0x03, 0xcf, 0x0a, 0xfa, 0xd1, 0x2b, 0x62,
	0x2f, 0x88, 0xbc, 0x92, 0xdf, 0x88, 0xf2, 0xdf, 0x03, 0xac, 0x38, 0x8f, 0xf0, 0x57, 0x89, 0x4a,
	0x33, 0x1f, 0x4c, 0xd4, 0x14, 0xce, 0x78, 0x31, 0x09, 0xa9, 0x0a, 0x29, 0xb6, 0xc8, 0x50, 0xfe,
	0x17, 0x18, 0x93, 0x43, 0xe5, 0x32, 0x53, 0xc8, 0x66, 0x60, 0x17, 0xa8, 0xca, 0xd4, 0x78, 0x86,
	0x51, 0x55, 0x31, 0x07, 0x06, 0xa4, 0xbf, 0x5c, 0x57, 0xb1, 0xd6, 0xa5, 0xbf, 0x84, 0x93, 0x1f,
	0xf9, 0x21, 0x9b, 0xff, 0x99, 0x1a, 0xc0, 0xb4, 0x36, 0xfd, 0x7b, 0xb0, 0xff, 0x0e, 0x4e, 0xd6,
	0x98, 0xe2, 0x43, 0xfb, 0xc6, 0x26, 0x56, 0x7b, 0x93, 0x00, 0xa6, 0xb5, 0xf4, 0x99, 0xa6, 0x1f,
	0x61, 0xfa, 0x15, 0xf5, 0x2a, 0x4d, 0x8f, 0xca, 0xb7, 0x60, 0x53, 0x1b, 0xe5, 0x58, 0x5e, 0xef,
	0xc9, 0xd6, 0x15, 0xb7, 0xf8, 0x63, 0xc1, 0x64, 0xd3, 0x78, 0xd0, 0x2c, 0x84, 0xde, 0x8a, 0x73,
	0xf6, 0xb2, 0x52, 0x3f, 0x64, 0xef, 0xb2, 0x26, 0x64, 0x86, 0xf8, 0x1d, 0xf6, 0x09, 0x6c, 0x73,
	0x37, 0x3b, 0xad, 0xf8, 0x56, 0x76, 0xee, 0xeb, 0x47, 0x68, 0xd3, 0x68, 0x6e, 0x3b, 0x1a, 0x5b,
	0xa9, 0x1c, 0x8d, 0xed, 0x00, 0xfc, 0x0e, 0x3b, 0x07, 0xdb, 0x9c, 0xca, 0x66, 0x4f, 0x1e, 0xed,
	0xe6, 0xf0, 0x9f, 0x8e, 0xd6, 0x76, 0x22, 0x7e, 0xe7, 0x62, 0xf2, 0x13, 0xc2, 0xf9, 0x67, 0x22,
	0xf3, 0xed, 0xd6, 0x26, 0xdb, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x8d, 0x53, 0xdb,
	0xd6, 0x03, 0x00, 0x00,
}
